version: "3.8"
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
  fastapi:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"